site_name: Adaptive Gaming Resource (Demo)
site_url: https://tjfentie.github.io/GAME-Resource-Test/

nav:
  - Start Here: index.md
  - Latest Updates: updates.md
  - Adaptive Gaming Equipment:
      - Overview: equipment.md
      - Alternative Access: alt-access.md
      - Controller Modifications: control-mods.md
      - Video Game Accessibility: video-game-accessibility.md
  - Video Game Basics:
      - How to Pick Games: pick-game.md
      - Video Game Literacy: video-game-literacy.md
  - Best Practices: 
      - Gaming Session Walkthrough: session-walkthrough.md
      - Tips and Tricks: tips-and-tricks.md
  - Gamer Profiles: profiles.md
  - GAME Checkpoint Resources: 
      - Pre Session Questionnaire: questionnaire.md
      - Equipment Lists: equipment-lists.md
      - Templates: templates.md
      - Marketing/Posters: marketing.md
  - Get Support: support.md
  - Download/print: print.md

theme:
  Logo: images
  name: material
  features:
    - navigation.footer # this addes previous and next buttons at the bottom
    - navigation.instant  # Optional: makes page loads feel faster
  palette:
    - scheme: default
      primary: custom # This tells MkDocs we are overriding via CSS
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - with-pdf
  - include-markdown

extra_css:
  - styles/extra.css